#include "sigmsgs.h"

Sigmsgs signals[] = {
	{"",	""},
	{"sighup",	"hangup"},
	{"sigint",	""},
	{"sigquit",	"quit"},
	{"sigill",	"illegal instruction"},
	{"sigtrap",	"trace trap"},
	{"sigabrt",	"abort"},
	{"sigemt",	"emt instruction"},
	{"sigfpe",	"floating point error"},
	{"sigkill",	"killed"},
	{"sigbus",	"bus error"},
	{"sigsegv",	"segmentation violation"},
	{"sigsys",	"invalid argument to system call"},
	{"sigpipe",	""},
	{"sigalrm",	"alarm clock"},
	{"sigterm",	"terminated"},
	{"sigurg",	"urgent condition on i/o channel"},
	{"sigstop",	"stopped by program"},
	{"sigtstp",	"stopped"},
	{"sigcont",	"continue"},
	{"sigchld",	"child stop or exit"},
	{"sigttin",	"background tty read"},
	{"sigttou",	"background tty write"},
	{"sigio",	"socket i/o possible"},
	{"sigxcpu",	"exceeded cpu time limit"},
	{"sigxfsz",	"exceeded file size limit"},
	{"sigvtalrm",	"virtual timer alarm"},
	{"sigprof",	"profiling timer alarm"},
	{"sigwinch",	"window size change"},
	{"siginfo",	"information request"},
	{"sigusr1",	"user defined signal 1"},
	{"sigusr2",	"user defined signal 2"},
};
