#!/bin/sh
#
# mailto-neomutt -- wrapper to use neomutt as mailto handler from Firefox
#
# If you want Firefox to use this wrapper for mailto URLs, go to Edit >
# Preferences > Applications, and set "mailto" to "/usr/libexec/neomutt/mailto-neomutt".

exec x-terminal-emulator -e neomutt "$@"
