#!/bin/sh

set -e

case "$1" in
	(remove)
	@MEMO_LAUNCHCTL_PREFIX@/bin/launchctl unload @MEMO_PREFIX@/Library/LaunchDaemons/org.freedesktop.dbus-session.plist
	;;
    (purge)
    @MEMO_LAUNCHCTL_PREFIX@/bin/launchctl unload @MEMO_PREFIX@/Library/LaunchDaemons/org.freedesktop.dbus-session.plist
    rm -f @MEMO_PREFIX@/var/lib/dbus/machine-id
    rmdir /var/lib/dbus || true
    ;;
	(*)
	exit 0
	;;
esac

exit 0
