#!/bin/sh

set -e

current_version="1.79.2"
docbook_location="file://@MEMO_PREFIX@@MEMO_SUB_PREFIX@/share/xml/docbook/stylesheet/docbook-xsl"
catalog_location="@MEMO_PREFIX@/etc/xml/catalog"

xmlcatalog --noout --del "${docbook_location}/catalog.xml" ${catalog_location}

for link in https://cdn.docbook.org/release/xsl-nons http://docbook.sourceforge.net/release/xsl; do
	for ver in current ${current_version}; do
		xmlcatalog --noout --del "${link}/${ver}" ${catalog_location}
	done
done

exit 0