#!/bin/sh

set -e

case "$1" in
  configure)
    update-alternatives --quiet --install /usr/bin/pager pager \
      /usr/bin/less 77 --slave /usr/share/man/man1/pager.1 \
      pager.1 /usr/share/man/man1/less.1
    update-alternatives --quiet --remove pager /bin/less
  ;;
  abort-upgrade|abort-remove|abort-deconfigure)
  ;;
  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 0
  ;;
esac



exit 0
