#!/bin/sh
set -e

if [ "$1" = "configure" ]; then
	# For now, just update the alternatives set to include us.
	update-alternatives --install /usr/bin/lua lua-interpreter /usr/bin/lua50 80 --slave /usr/share/man/man1/lua.1.gz lua-manual /usr/share/man/man1/lua50.1.gz
	update-alternatives --install /usr/bin/luac lua-compiler /usr/bin/luac50 80 --slave /usr/share/man/man1/luac.1.gz lua-compiler-manual /usr/share/man/man1/luac50.1.gz
fi

