#!/bin/sh
set -e

if [ "$1" = "configure" ]; then
	# For now, just update the alternatives set to include us.
	update-alternatives --install @MEMO_PREFIX@@MEMO_SUB_PREFIX@/bin/lua lua-interpreter @MEMO_PREFIX@@MEMO_SUB_PREFIX@/bin/lua50 80 --slave @MEMO_PREFIX@@MEMO_SUB_PREFIX@/share/man/man1/lua.1.zst lua-manual @MEMO_PREFIX@@MEMO_SUB_PREFIX@/share/man/man1/lua50.1.zst
	update-alternatives --install @MEMO_PREFIX@@MEMO_SUB_PREFIX@/bin/luac lua-compiler @MEMO_PREFIX@@MEMO_SUB_PREFIX@/bin/luac50 80 --slave @MEMO_PREFIX@@MEMO_SUB_PREFIX@/share/man/man1/luac.1.zst lua-compiler-manual @MEMO_PREFIX@@MEMO_SUB_PREFIX@/share/man/man1/luac50.1.zst
fi

