#!/bin/sh

set -e

update-alternatives --quiet --install @MEMO_PREFIX@@MEMO_SUB_PREFIX@/bin/awk awk @MEMO_PREFIX@@MEMO_SUB_PREFIX@/bin/mawk 5 \
  --slave @MEMO_PREFIX@@MEMO_SUB_PREFIX@/share/man/man1/awk.1.zst awk.1.zst @MEMO_PREFIX@@MEMO_SUB_PREFIX@/share/man/man1/mawk.1.zst \
  --slave @MEMO_PREFIX@@MEMO_SUB_PREFIX@/bin/nawk nawk @MEMO_PREFIX@@MEMO_SUB_PREFIX@/bin/mawk \
  --slave @MEMO_PREFIX@@MEMO_SUB_PREFIX@/share/man/man1/nawk.1.zst nawk.1.zst @MEMO_PREFIX@@MEMO_SUB_PREFIX@/share/man/man1/mawk.1.zst
