#!/bin/sh

set -eu

USER="redis"
GROUP="$USER"
CONFFILE="@MEMO_PREFIX@/etc/redis/redis.conf"

if [ "$1" = "configure" ]
then
	if ! dpkg-statoverride --list ${CONFFILE} >/dev/null 2>&1
	then
		dpkg-statoverride --update --add ${USER} ${GROUP} 640 ${CONFFILE}
	fi
fi

#DEBHELPER#

if [ "$1" = "configure" ]
then
	@GNU_PREFIX@find @MEMO_PREFIX@/etc/redis -maxdepth 1 -type d -name 'redis-server.*.d' -empty -delete
fi

exit 0
