[llvm]
optimize = true
ccache = true
targets = "AArch64;ARM;X86"

[build]
host = ["PROCURSUS_TARGET"]
build-dir = "PROCURSUS_BUILD_DIR"
extended = true
tools = ["cargo", "clippy", "analysis", "src"]

[install]
prefix = "PROCURSUS_INSTALL_PREFIX"
sysconfdir = "etc"

[rust]
optimize = true
incremental = true
parallel-compiler = true
default-linker = "clang"
channel = "nightly"