#!/bin/sh
set -e
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ]; then
        update-alternatives --install @MEMO_PREFIX@@MEMO_SUB_PREFIX@/bin/unrar unrar @MEMO_PREFIX@@MEMO_SUB_PREFIX@/bin/unrar-nonfree 40 \
            --slave @MEMO_PREFIX@@MEMO_SUB_PREFIX@/share/man/man1/unrar.1@MEMO_MANPAGE_SUFFIX@ unrar.1@MEMO_MANPAGE_SUFFIX@ @MEMO_PREFIX@@MEMO_SUB_PREFIX@/share/man/man1/unrar-nonfree.1@MEMO_MANPAGE_SUFFIX@
fi
